# Generated by Django 3.2.9 on 2021-12-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendedor_user', serialize=False, to='auth.user')),
                ('username', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('lider', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vendedor',
                'db_table': 'Usuarios',
            },
        ),
    ]
