# Generated by Django 3.2.9 on 2022-01-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendedores',
            table='vendedores',
        ),
    ]
