# Generated by Django 3.2.9 on 2022-01-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_vendedores_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendedores',
            table='usuarios',
        ),
    ]
