# Generated by Django 3.2.9 on 2021-12-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('oh', models.PositiveIntegerField(default=0)),
                ('arribo', models.PositiveIntegerField(default=0)),
                ('mx', models.PositiveIntegerField(default=0)),
                ('gdl', models.PositiveIntegerField(default=0)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('voltaje_min', models.PositiveIntegerField(blank=True, null=True)),
                ('voltaje_max', models.PositiveIntegerField(blank=True, null=True)),
                ('potencia_w', models.PositiveIntegerField(blank=True, null=True)),
                ('temperatura_k', models.PositiveIntegerField(blank=True, null=True)),
                ('flujo_luminoso', models.PositiveIntegerField(blank=True, null=True)),
                ('vida_promedio_hrs', models.PositiveIntegerField(blank=True, null=True)),
                ('piezasxcaja', models.PositiveIntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_catalogo', to='catalogo.stock')),
            ],
            options={
                'db_table': 'Catalogo',
            },
        ),
    ]
