# Generated by Django 3.2.9 on 2022-01-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=250, unique=True)),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('califiacion', models.SmallIntegerField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendedores')),
            ],
            options={
                'verbose_name': 'Ojetivo por cliente',
                'db_table': 'Ojetivo por cliente',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendedores')),
            ],
            options={
                'verbose_name': 'Objetivos',
                'db_table': 'Objetivo',
            },
        ),
    ]
