# Generated by Django 3.2.9 on 2022-01-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objetivo',
            table='objetivo',
        ),
        migrations.AlterModelTable(
            name='objetivocliente',
            table='objetivo_x_cliente',
        ),
    ]
