# Generated by Django 3.2.9 on 2022-01-04 18:50

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('giro', models.CharField(blank=True, choices=[('material electrico', 'MATERIAL ELÉCTRICO'), ('tienda iluminacion', 'TIENDA DE ILUMINACIÓN'), ('eco tecnologias', 'ECO TECNOLOGÍAS'), ('ferre flectricos', 'FERRÉ ELÉCTRICOS'), ('otros', 'OTORS')], max_length=20, null=True)),
                ('actividad_principal', models.CharField(choices=[('mayorista', 'MAYORISTA'), ('venta al detalle', 'VENTA AL DETALLE'), ('proyectos', 'PROYECTOS'), ('mostrador', 'MOSTRADOR'), ('otros', 'OTROS')], max_length=20)),
                ('igoto', models.BooleanField(default=False)),
                ('geo_power', models.BooleanField(default=False)),
                ('tecnolite', models.BooleanField(default=False)),
                ('philco', models.BooleanField(default=False)),
                ('boomer', models.BooleanField(default=False)),
                ('win_led', models.BooleanField(default=False)),
                ('arlite', models.BooleanField(default=False)),
                ('lumiance', models.BooleanField(default=False)),
                ('led_vance', models.BooleanField(default=False)),
                ('magg', models.BooleanField(default=False)),
                ('energain', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('tamano_empresa', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Valor nulo'), (10, 'HASTA 10 EMPLEADOS'), (50, 'HASTA 50 EMPLEADOS'), (250, 'HASTA 250 EMPLEADOS'), (251, 'MÁS DE 250 EMPLEADOS')], null=True)),
                ('calificacion', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('prospecto', 'PROSPECTO'), ('cliente', 'CLIENTE')], default='prospecto', max_length=20, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_cliente', to='users.vendedores')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('numero_telefono', models.PositiveBigIntegerField(validators=[crm.models.contacto.validate_length])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(max_length=20)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('datos_adicionales', models.TextField(blank=True)),
                ('nombre_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_contacto', to='crm.clientes')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_contacto', to='users.vendedores')),
            ],
            options={
                'verbose_name': 'contacto',
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_o_salida', models.CharField(choices=[('entrada', 'ENTRADA'), ('salida', 'SALIDA')], max_length=20)),
                ('tipo_llamada', models.CharField(choices=[('prospeccion', 'PROSPECCIÓN'), ('cita', 'VISITA CON CITA (PRESENTACIÓN DE PRODUCTO)'), ('saludo', 'VISITA SALUDO (COBRANZA, GARANTÍA)'), ('cierre', 'CIERRE'), ('propuesta', 'PROPUESTA DEL MES')], max_length=20)),
                ('fecha_sig_cont', models.DateField()),
                ('comentario', models.TextField(blank=True)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('nombre_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_visitas', to='crm.clientes')),
                ('nombre_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_visitas', to='crm.contacto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_visita', to='users.vendedores')),
            ],
            options={
                'verbose_name': 'visita',
                'db_table': 'visita',
            },
        ),
        migrations.CreateModel(
            name='llamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_o_salida', models.CharField(choices=[('entrada', 'ENTRADA'), ('salida', 'SALIDA')], max_length=20)),
                ('tipo_llamada', models.CharField(choices=[('prospeccion', 'PROSPECCIÓN'), ('cita', 'HACER CITA'), ('seguimiento', 'SEGUIMIENTO'), ('cierre', 'CIERRE')], max_length=20)),
                ('fecha_sig_cont', models.DateField()),
                ('comentario', models.TextField(blank=True)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('nombre_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_llamadas', to='crm.clientes')),
                ('nombre_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_llamadas', to='crm.contacto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_llamada', to='users.vendedores')),
            ],
            options={
                'verbose_name': 'llamada',
                'db_table': 'llamadas',
            },
        ),
    ]
