# Generated by Django 3.2.9 on 2022-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'cliente'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='llamadas',
            name='creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
    ]
