# Generated by Django 3.2.9 on 2022-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20220104_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='llamadas',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
